version: "3.9"
services:
  # Database
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p", "user_password"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - prestashop_network
  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    build:
      context: ./build/phpmyadmin
      dockerfile: Dockerfile
    volumes:
      - ./phpmyadmin/themes:/var/www/html/themes
    links:
      - mysql
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - prestashop_network
  # Prestashop
  prestashop:
    depends_on:
      - mysql
    build:
      context: ./build/prestashop
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./prestashop:/var/www/html
      - ./logs:/var/www/html/var/logs
      #- type: bind
      #  source: ./modules/testModule # local path to the module
      #  target: /var/www/html/modules/testModule # path to be mounted in the container
      #- type: bind
      #  source: ./themes/myTheme # local path to the theme
      #  target: /var/www/html/themes/myTheme # path to be mounted in the container
    env_file: .env
    environment:
      PS_DEV_MODE: $PS_DEV_MODE
      PS_HOST_MODE: $PS_HOST_MODE
      PS_DEMO_MODE: $PS_DEMO_MODE
      DB_SERVER: mysql
      DB_USER: $MYSQL_USER
      DB_PASSWD: $MYSQL_PASSWORD
      DB_PREFIX: $DB_PREFIX
      DB_NAME: $MYSQL_DATABASE
      PS_INSTALL_AUTO: $PS_INSTALL_AUTO
      PS_DOMAIN: $PS_DOMAIN
      PS_ERASE_DB: $PS_ERASE_DB
      PS_INSTALL_DB: $PS_INSTALL_DB
      PS_LANGUAGE: $PS_LANGUAGE
      PS_COUNTRY: $PS_COUNTRY
      PS_ALL_LANGUAGES: $PS_ALL_LANGUAGES
      PS_FOLDER_ADMIN: $PS_FOLDER_ADMIN
      PS_FOLDER_INSTALL: $PS_FOLDER_INSTALL
      PS_ENABLE_SSL: $PS_ENABLE_SSL
      ADMIN_MAIL: $ADMIN_MAIL
      ADMIN_PASSWD: $ADMIN_PASSWD
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  mysql:
  prestashop:
  logs:
  phpmyadmin:
