services:
  # Database
  mysql:
    image: mysql:latest
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql  # Use named volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - prestashop_network

  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - prestashop_network

  # Prestashop
  prestashop:
    depends_on:
      - mysql
    build:
      context: ./build/prestashop
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    env_file: .env
    environment:
      DB_SERVER: mysql
      DB_USER: $MYSQL_USER
      DB_PASSWD: $MYSQL_PASSWORD
      DB_PREFIX: $DB_PREFIX
      DB_NAME: $MYSQL_DATABASE
      PS_DEV_MODE: $PS_DEV_MODE
      PS_HOST_MODE: $PS_HOST_MODE
      PS_DEMO_MODE: $PS_DEMO_MODE
      PS_INSTALL_AUTO: $PS_INSTALL_AUTO
      PS_DOMAIN: $PS_DOMAIN
      PS_ERASE_DB: $PS_ERASE_DB
      PS_INSTALL_DB: $PS_INSTALL_DB
      PS_LANGUAGE: $PS_LANGUAGE
      PS_COUNTRY: $PS_COUNTRY
      PS_ALL_LANGUAGES: $PS_ALL_LANGUAGES
      PS_FOLDER_ADMIN: $PS_FOLDER_ADMIN
      PS_FOLDER_INSTALL: $PS_FOLDER_INSTALL
      PS_ENABLE_SSL: $PS_ENABLE_SSL
      ADMIN_MAIL: $ADMIN_MAIL
      ADMIN_PASSWD: $ADMIN_PASSWD
    working_dir: /var/www/html
    volumes:
      - ./prestashop_data:/var/www/html          # Main Prestashop files
      - ./logs:/var/www/html/var/logs            # Log files
      # Uncomment below for custom modules and themes
      #- ./modules/testModule:/var/www/html/modules/testModule
      #- ./themes/myTheme:/var/www/html/themes/myTheme
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  mysql_data:            # MySQL data storage
  prestashop_data:       # Prestashop data storage
  logs:                  # Log data
